name: Download translations

on:
  workflow_dispatch:
  #scheduled:
    # run daily at 00:00.
  #  - cron: '0 0 * * *'

permissions:
  pull-requests: write

jobs:
  translations:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Download translations from Translation Project
      run: |
        ./download-translations

    - name: Output the new and changed translation files
      id: pofiles
      run: |
        echo "new=$(git status -s po/*.po | grep '^??' | sed 's|^?? ||' | tr '\n' ' ')" >> $GITHUB_OUTPUT
        echo "changed=$(git status -s po/*.po | grep '^ M' | sed 's|^ M ||' | tr '\n' ' ')" >> $GITHUB_OUTPUT

    - name: Update LINGUAS with new languages, if any
      run: |
        if [ -n "${{ steps.pofiles.outputs.new }}" ]; then
          langs=$(echo "${{ steps.pofiles.outputs.new }}" | sed 's|po/||g;s|\.po||g')
          echo "Adding to po/LINGUAS: $langs"
          echo "$langs" >> po/LINGUAS
          (tr ' ' '\n' | sort -u) < po/LINGUAS > tmp 
          (tr '\n' ' ' | sed 's|^ ||;s| $||') < tmp > po/LINGUAS
          rm tmp
        else
          echo "No new translation files, po/LINGUAS not changed."
        fi

    - run: git status    
    - run: git diff --patch

    - name: Commit changes
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add po/*.po po/LINGUAS
        if ! git diff-index --cached --quiet HEAD "$NEW"; then
          git commit -m 'po: add new translations' "$NEW" po/LINGUAS
        fi
        if ! git diff-index --cached --quiet HEAD "$CHANGED"; then
          git commit -m 'po: add new translations' "$CHANGED"
        fi
      env:
        NEW: "${{ steps.pofiles.outputs.new }}"
        CHANGED: "${{ steps.pofiles.outputs.changed }}"

    - run: git log
    - run: git log -p1
 
    #- name: Create pull request
    #  uses: peter-evans/create-pull-request@v6
    #  with:
    #    add-paths: |
    #      po/*.po
    #      po/LINGUAS
    #    commit-message:
    #    branch: create-pull-request/translations
    #    title: Update translates from Translation Project
    #    body: 
    #    commit-message: |
       
    
