name: Download translations

on:
  workflow_dispatch:
  #scheduled:
    # run daily at 00:00.
  #  - cron: '0 0 * * *'

permissions:
  pull-requests: write

jobs:
  translations:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Download translations from Translation Project
      run: |
        ./download-translations

    - name: Output list of languages files
      id: pofiles
      run: |
        echo "new=$(git status -s po/*.po | grep '^??' | sed 's|^?? ||')" >> GITHUB_OUTPUT
        echo "changed=$(git status -s po/*.po | grep '^ M' | sed 's|^ M ||')" >> GITHUB_OUTPUT

    - name: Update LINGUAS with new languages, if any
      run: >-
        if [ -n "${{ steps.pofiles.outputs.new }}" ]; then
          langs=$(echo "${{ steps.pofiles.outputs.new }}" | sed 's|po/||g;s|\.po||g')
          echo "INFO: Adding language codes to po/LINGUAS: $langs"
          for l in "$langs"; do echo $l >> po/LINGUAS; done
          sort -u po/LINGUAS > po/LINGUAS.tmp
          mv po/LINGUAS.tmp po/LINGUAS
        else
          echo "No new translation files, po/LINGUAS not changed."
        fi

    - run: git status    
    - run: git diff --patch

    #- name: Create pull request
    #  uses: peter-evans/create-pull-request@v6
    #  with:
    #    add-paths: |
    #      po/*.po
    #      po/LINGUAS
    #    commit-message:
    #    branch: create-pull-request/translations
    #    title: Update translates from Translation Project
    #    body: 
    #    commit-message: |
       
    
